Esmax/Controllers/PlanAccion/MplanAccionController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using Esmax.Models;
using Esmax.Models.MplanAccion;

namespace Esmax.Controllers.PlanAccion
{
    public class PA
    {
        public string accion { get; set; }
        public string responsable_id { get; set; }
        public int cumplimiento { get; set; }
    }

    public class paUser
    {
        public int plan_accion_id { get; set; }
        public string accion { get; set; }
        public int modulo { get; set; }
        public DateTime cumplimiento { get; set; }
        public string estado { get; set; }
        public string UserName { get; set; }
    }

    public class datos
    {
        public int modulo { get; set; }
        public int total { get; set; }
    }
    
    public class datos2
    {
        public string UserName { get; set; }
        public int total { get; set; }
    }
    public class imagenes
    {
        public HttpPostedFileBase files { get; set; }
    }
    public class MplanAccionController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        // GET: MplanAccion
        [Authorize]
        public ActionResult ingresarPlanAccion()
        {
            return View("ingresarPlanAccion", "_Layout");
        }

        [HttpPost]
        [Authorize]
        public JsonResult addPlanAccion(PA planAccion, List<TareasPlanAccion> tareas)
        {
            var plan = db.PlanAccion.Add(new Models.PlanAccion
            {
                accion = planAccion.accion,
                responsable_id = planAccion.responsable_id,
                cumplimiento = DateTime.Now.AddDays(Convert.ToDouble(planAccion.cumplimiento)),
                created_at = DateTime.Now,
                modulo = 3
            });
            

            foreach (var tarea in tareas)
            {
                db.TareasPlanAccions.Add(new TareasPlanAccion
                {
                    tareas_descripcion = tarea.tareas_descripcion,
                    plan_accion_id = plan.plan_accion_id,
                    created_at = DateTime.Now
                });
                
            }
            db.SaveChanges();
            
            db.Notificaciones.Add(new Notificaciones
            {
                descripcion = "Tienes un nuevo plan de acción. ''" + plan.accion + "''",
                modulo = 3,
                plan_accion_id = plan.plan_accion_id,
                UserId = plan.responsable_id,
                created_at = DateTime.Now
            });
            db.SaveChanges();

            var user = db.Users.Where(x => x.Id == planAccion.responsable_id).FirstOrDefault();
            
            try
            {
                MailMessage correo = new MailMessage();
                correo.From = new MailAddress("sistemapaso@esmax.cl"); //correo que usara la app
                correo.To.Add(user.Email);
                correo.Subject = "Tienes un nuevo plan de accion asociado";
                correo.Body = user.UserName + ", <br/><br/> Tiene un nuevo plan de acción, Número de folio: " + plan.plan_accion_id + " <br/><br/> Haz click aqui para acceder: http://paso.esmax.cl/MplanAccion/ver/"+plan.plan_accion_id+ "<br><br><br> Por favor no responder este correo.";
                correo.IsBodyHtml = true;
                correo.Priority = MailPriority.Normal;

                SmtpClient smtp = new SmtpClient();
                smtp.Host = "smtp.esmax.cl";
                smtp.Port = 25;
                smtp.EnableSsl = true;
                smtp.UseDefaultCredentials = true;
                string sCuentaCorreo = "sistemapaso@esmax.cl";
                string sPasswordCorreo = "";
                smtp.Credentials = new System.Net.NetworkCredential(sCuentaCorreo, sPasswordCorreo);

                smtp.Send(correo);
                ViewBag.Mensaje = "Mensaje enviado correctamente";
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
            }
            
            return Json("saved");
        }

        [Authorize]
        public ActionResult revisar()
        {
            return View("revisar", "_Layout");
        }

        [HttpPost]
        [Authorize]
        public JsonResult getPlanAccion(string id)
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<Models.PlanAccion> lista = db.PlanAccion.Where(x => x.responsable_id == id).Where( e => e.estado == "habilitado").ToList();
            return Json(lista);
        }
        
        
        [HttpPost]
        [Authorize]
        public JsonResult cerrarPlanAccion(int id, string descripcion)
        {
            db.Configuration.ProxyCreationEnabled = false;
            var planAccion = db.PlanAccion.Where(x => x.plan_accion_id == id).FirstOrDefault();
            planAccion.estado = "cerrado";
            planAccion.descripcionCierre = descripcion;
            db.SaveChanges();
            
            return Json("plan de accion cerrado");
        }
        
        [HttpGet]
        [Authorize]
        public ActionResult GraficosPlanAccion()
        {
            return View("Graficos", "_Layout");
        }

        
        [HttpPost]
        [Authorize]
        public JsonResult getTareas(int id)
        {
            db.Configuration.ProxyCreationEnabled = false;
            List<TareasPlanAccion> lista = db.TareasPlanAccions.Where(x => x.plan_accion_id == id).ToList();
            return Json(lista);
        }
        
        
        [HttpPost]
        [Authorize]
        public JsonResult getModulos(string desde, string hasta)
        {
            List<datos> lst = new List<datos>();
            using (SqlConnection con = new SqlConnection(cs))
            {
                con.Open();
                string query = @"select modulo, COUNT(modulo) as total  from PlanAccions  where created_at >= @desde and created_at <= @hasta group by modulo"; 
                SqlCommand com = new SqlCommand(query, con);
                com.Parameters.AddWithValue("@desde", desde);
                com.Parameters.AddWithValue("@hasta", hasta);
                SqlDataReader rdr = com.ExecuteReader();
                while (rdr.Read())
                {
                    lst.Add(new datos
                    {
                        modulo = Convert.ToInt32(rdr["modulo"] is DBNull ? 0: rdr["modulo"]),
                        total = Convert.ToInt32(rdr["total"] is DBNull ? 0: rdr["total"])
                        
                    });
                }
                return Json(lst);
            } 
        }
        
        [HttpPost]
        [Authorize]
        public JsonResult getUsuariosResponsables(string desde, string hasta)
        {
            List<datos2> lst = new List<datos2>();
            using (SqlConnection con = new SqlConnection(cs))
            {
                con.Open();
                string query = @"select top 5 ApplicationUsers.UserName, COUNT(PlanAccions.responsable_id) as total from PlanAccions inner join ApplicationUsers ON PlanAccions.responsable_id = ApplicationUsers.Id where created_at >= @desde and created_at <= @hasta group by UserName order by total desc"; 
                SqlCommand com = new SqlCommand(query, con);
                com.Parameters.AddWithValue("@desde", desde);
                com.Parameters.AddWithValue("@hasta", hasta);
                SqlDataReader rdr = com.ExecuteReader();
                while (rdr.Read())
                {
                    lst.Add(new datos2
                    {
                        UserName = Convert.ToString(rdr["UserName"] is DBNull ? 0: rdr["UserName"]),
                        total = Convert.ToInt32(rdr["total"] is DBNull ? 0: rdr["total"])
                        
                    });
                }
                return Json(lst);
            } 
        }
        
        [HttpPost]
        [Authorize]
        public JsonResult getUsuariosResponsablesHabilitados(string desde, string hasta)
        {
            List<datos2> lst = new List<datos2>();
            using (SqlConnection con = new SqlConnection(cs))
            {
                con.Open();
                string query = @"select top 5 ApplicationUsers.UserName, COUNT(PlanAccions.responsable_id) as total from PlanAccions inner join ApplicationUsers ON PlanAccions.responsable_id = ApplicationUsers.Id where created_at >= @desde and created_at <= @hasta and PlanAccions.estado = @estado group by UserName order by total desc"; 
                SqlCommand com = new SqlCommand(query, con);
                com.Parameters.AddWithValue("@desde", desde);
                com.Parameters.AddWithValue("@hasta", hasta);
                com.Parameters.AddWithValue("@estado", "habilitado");
                SqlDataReader rdr = com.ExecuteReader();
                while (rdr.Read())
                {
                    lst.Add(new datos2
                    {
                        UserName = Convert.ToString(rdr["UserName"] is DBNull ? 0: rdr["UserName"]),
                        total = Convert.ToInt32(rdr["total"] is DBNull ? 0: rdr["total"])
                        
                    });
                }
                return Json(lst);
            } 
        }
        
        [HttpPost]
        [Authorize]
        public JsonResult getUsuariosResponsablesCerrados(string desde, string hasta)
        {
            List<datos2> lst = new List<datos2>();
            using (SqlConnection con = new SqlConnection(cs))
            {
                con.Open();

Esmax/Views/MplanAccion/Calendar.cshtml
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Revisar plan de accion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles
{
    <link href='~/assets/fullCalendar/packages/core/main.css' rel='stylesheet' />
    <link href='~/assets/fullCalendar/packages/daygrid/main.css' rel='stylesheet' />
    <link href='~/assets/fullCalendar/packages/bootstrap/main.css' rel='stylesheet' />
    <link href='~/assets/fullCalendar/packages/timegrid/main.css' rel='stylesheet' />
    <link href='~/assets/fullCalendar/packages/list/main.css' rel='stylesheet' />
    <style>
        .fc-day-grid-event .fc-time {
            font-weight: bold;
            display: none;
        }
    </style>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.css">

}


<div class="container">
    <div class="row justify-content-center mb-5">
        <div class=" col-lg-11 mt-3 mb-3" style="padding-left: 15px">
            <a class="btn btn-info" style="font-size: 100%;" href="@Url.Action("calendar", "MplanAccion")">
                <i class="fa fa-list-ul fa-2x mr-2"></i> Calendario
            </a>
            <a class="btn btn-secondary" style="font-size: 75%;" v-if="user.Rol === 'Administrador'" href="@Url.Action("ingresarPlanAccion","MplanAccion")">
                <i class="fa fa-plus fa-2x mr-2"></i> Crear plan de acci&oacute;n
            </a>
            <a class="btn btn-secondary" style="font-size: 75%;" href="@Url.Action("revisar","MplanAccion")">
                <i class="fa fa-edit fa-2x mr-2"></i> Revisar plan de acci&oacute;n
            </a>
            <a class="btn btn-secondary"style="font-size: 75%;" href="@Url.Action("GraficosPlanAccion", "MplanAccion")">
                <i class="fa fa-chart-line fa-2x mr-2"></i> Gr&aacute;ficas plan de acci&oacute;n
            </a>
        </div>
        <div class="col-lg-11">
            <div class="card shadow-sm">
                <div class="card-body">
                    <div id='calendar'></div>
                </div>
                
            </div>
            
        </div>
       
    </div>
    
</div>


@section scripts{
    <script src='~/assets/fullCalendar/packages/core/main.js'></script>
    <script src='~/assets/fullCalendar/packages/daygrid/main.js'></script>
    <script src='~/assets/fullCalendar/packages/bootstrap/main.js'></script>
    <script src='~/assets/fullCalendar/packages/timegrid/main.js'></script>
    <script src='~/assets/fullCalendar/packages/list/main.js'></script>
    <script src='~/assets/fullCalendar/packages/core/locales/es.js'></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.2/jquery-confirm.min.js"></script>

    <script>
        var ert = new Vue({
            el: '#app',
            data() {
                return{
                    user: null,
                    idTarea: null,
                }
            },
            created() {
                this.getUser();
                this.obtenerId();
            },
            mounted() {

            },
            methods: {
                getUser() {
                    var urlUser = '@Url.Action("getUser", "User")';

                    var data = {
                        id: '@User.Identity.GetUserId()'
                    }

                    axios.post(urlUser, data).then(response => {
                        this.user = response.data;
                    }).catch(error => {
                        console.log("error: " + error);
                    })
                },

            }
        });

        

        document.addEventListener('DOMContentLoaded',
            function() {


                //Defino un arreglo vacio
                var e = [];

                //Url a donde va a buscar los datos
                var url = "@Url.Action("getPlanAccion", "MplanAccion")";

                //id del usuario actual
                var data = {
                    id: @User.Identity.GetUserId()
                }

                //envio los datos(id) a la url para obtener los datos
                axios.post(url, data).then(response => {
                    //proceso los datos que me responde el controlador para formar el arreglo
                    var datos = response.data;
                    var context = [];
                    datos.map(function(d) {
                        var modulo = "";
                        if (d.modulo === 1) {
                            modulo = "ODT";
                        }
                        if (d.modulo === 2) {
                            modulo = "RSMS";
                        }
                        if (d.modulo === 3) {
                            modulo = "PLAN DE ACCION";
                        }
                        if (d.modulo === 5) {
                            modulo = "RTA";
                        }
                        e.push({
                            title: d.accion,
                            start: formatDate(d.cumplimiento),
                            end: formatDate(d.cumplimiento),
                            color: getColor(d.modulo),
                            id: d.plan_accion_id,
                            groupId: modulo
                        })
                    })
                    console.log(e);
                    getCalendar(e);

                }).catch(error => {
                    console.log("error: " + error);
                })

                function getColor(modulo) {
                    if (modulo === 1) {
                        return '#007BFF';
                    } else if (modulo === 3) {
                        return '#26C6DA';
                    } else if (modulo === 2) {
                        return '#2DB27D';
                    } else if (modulo === 5) {
                        return '#6F5091';
                    }
                }

                function getCalendar(e) {
                    console.log("mostrando datos en e");
                    console.log(e);
                    var calendarEl = document.getElementById('calendar');


                    var calendar = new FullCalendar.Calendar(calendarEl,
                        {
                            plugins: ['dayGrid', 'timeGrid', 'list', 'bootstrap'],
                            eventLimit: true,
                            buttonText: {
                                today: 'Hoy',
                                month: 'Mes',
                                week: 'Semana',
                                day: 'Dia',
                                list: 'Lista'
                            },
                            header: {
                                left: 'prev,next today myCustomButton',
                                center: 'title',
                                right: 'dayGridMonth,timeGridWeek,timeGridDay'
                            },
                            themeSystem: 'bootstrap',
                            weekNumbers: true,
                            events: e,
                            locale: 'es',
                            eventClick: function(info) {
                                var fecha = new Date(info.event.start);
                                var dia = fecha.getDate();
                                var mes = fecha.getMonth()+1;
                                var anio = fecha.getFullYear();
                                $.confirm({
                                    title: info.event.title,
                                    columnClass: 'medium',
                                    content: ''+
                                        '<div class="container mt-4 mb-3">'+
                                        '<div class="row">'+
                                        '<div class="col-lg-6">'+
                                        '<h6 style="font-weight: bold">Modulo </h6>'+
                                        '</div>'+
                                        '<div class="col-lg-6">'+
                                        '<h6>'+ info.event.groupId +'</h6>'+
                                        '</div>'+
                                        '</div>'+
                                        '<div class="row">'+
                                        '<div class="col-lg-6">'+
                                        '<h6 style="font-weight: bold">Fecha de cumplimiento </h6>'+
                                        '</div>'+
                                        '<div class="col-lg-6">'+
                                        '<h6>'+ dia + '/' + mes + '/' + anio + '</h6>'+
                                        '</div>'+
                                        '</div>'+
                                        '</div>'+
                                        '</div>',
                                    buttons: {
                                        Acceder: function () {
                                            window.location = "@Url.Action("ver","MplanAccion")/" + info.event.id;
                                        },
                                        cancelar: function () {
                                            
                                        }
                                        
                                    }
                                });
                            }

                        });

                    calendar.render();
                }


                function formatDate(date) {

                    var fecha = date,
                        patron = "/Date(",
                        valor = "",
                        nuevo = fecha.replace(patron, valor),
                        patron2 = ")/",
                        valor2 = "",
                        nuevo2 = nuevo.replace(patron2, valor2);

                    var int = parseInt(nuevo2);

                    var d = new Date(int);

                    var monthNames = [
                        "01", "02", "03",
                        "04", "05", "06", "07",
                        "08", "09", "10",
                        "11", "12"
                    ];
                    var day = d.getDate();
                    var monthIndex = d.getMonth();
                    var year = d.getFullYear();

                    return year + '-' + monthNames[monthIndex] + '-' + day;

                }

            });

    </script>
}

Esmax/Views/MplanAccion/modificarPA.cshtml
@using Microsoft.AspNet.Identity

@{
    ViewBag.Title = "Modificar plan de accion";
    Layout = "~/Views/Shared/_Layout.cshtml";
}